# Generated by Django 5.1.6 on 2025-03-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='example',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placeholder',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date')], default='text', max_length=10),
        ),
    ]
