# Generated by Django 5.1.7 on 2025-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_placeholder_example_placeholder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
