# Generated by Django 5.1.7 on 2025-03-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttemplate_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='html_content',
        ),
    ]
