# Generated by Django 5.1.7 on 2025-04-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_submitteddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitteddocument',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted_documents/'),
        ),
    ]
