# Generated by Django 5.1.7 on 2025-04-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_submitteddocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitteddocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='submitteddocument',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='submitteddocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='submitteddocument',
            name='generated_file',
        ),
    ]
