# Generated by Django 5.1.7 on 2025-04-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_submitteddocument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitteddocument',
            name='data',
        ),
        migrations.AddField(
            model_name='submitteddocument',
            name='document',
            field=models.FileField(null=True, upload_to='submitted_documents/'),
        ),
    ]
