# Generated by Django 5.1.7 on 2025-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_submitteddocument_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteddocument',
            name='document',
            field=models.FileField(default='temporary.txt', upload_to='submitted_documents/'),
            preserve_default=False,
        ),
    ]
