# Generated by Django 5.2 on 2025-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_approveddocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteddocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
